#!/bin/sh
set -e

case "$1" in
    configure)

	[ -f /etc/default/kafka ] && . /etc/default/kafka
	[ -z "$KAFKA_USER" ] && KAFKA_USER="kafka"
	[ -z "$KAFKA_GROUP" ] && KAFKA_GROUP="kafka"
	if ! getent group "$KAFKA_GROUP" > /dev/null 2>&1 ; then
	    addgroup --system "$KAFKA_GROUP" --quiet
	fi
	if ! id $KAFKA_USER > /dev/null 2>&1 ; then
	    adduser --system --home /usr/lib/kafka --no-create-home \
		--ingroup "$KAFKA_GROUP" --disabled-password --shell /bin/false \
		"$KAFKA_USER"
	fi

	# Set user permissions on /var/log/kafka and /usr/lib/kafka
	mkdir -p /var/log/kafka /usr/lib/kafka
	chown -R $KAFKA_USER:$KAFKA_GROUP /var/log/kafka /usr/lib/kafka
	chmod 755 /var/log/kafka /usr/lib/kafka

    # symlink log directory
    ln -s /var/log/kafka /usr/lib/kafka/logs

    # symlink config directory
    ln -s /etc/kafka /usr/lib/kafka/config

	# configuration files should not be modifiable by kafka user, as this can be a security issue
	chown -Rh root:root /etc/kafka/*
	chmod 755 /etc/kafka
	chmod 644 /etc/kafka/*
    ;;

esac


if [ -x "/etc/init.d/kafka" ]; then
	update-rc.d kafka defaults 95 10 >/dev/null
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d kafka start || true
	else
		/etc/init.d/kafka start || true
	fi
fi