#!/bin/sh
set -e

if [ -x "/etc/init.d/kafka" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d kafka stop || true
	else
		/etc/init.d/kafka stop || true
	fi
fi

rm -f /usr/lib/kafka/logs /usr/lib/kafka/config
